[project]
name = "streamlit-hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "streamlit>=1.50.0",
    "watchdog>=6.0.0",
    "wheel>=0.45.1",
]
